### ISSUE TITLE
Error "unexpected input coverage_file" when using example from README

### ISSUE THREAD

**Issue by mattwelke** [sidx1024/coverage-reporter-action#30]
Tried using in my workflow, starting from the example in the README.

My step looked like this (I tweaked the coverage folder name so that it was the default folder name used by `nyc`):

```yaml
- name: Report NYC coverage
  uses: sidx1024/report-nyc-coverage-github-action@v1.1
  with:
    coverage_file: "coverage/coverage-summary.json"
```

I get the following error:

```
Unexpected input(s) 'coverage_file', valid inputs are ['coverage_output_directory', 'comment_template_file', 'comment_mode', 'github_token', 'sources_base_path', 'files_coverage_table_output_type_order']
```
